name: build apple silicon joplin
on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install macOS dependencies
        run: |
          brew install gettext
          brew install translate-toolkit
          brew install vips

      - uses: actions/checkout@v3
        with:
          repository: 'laurent22/joplin'
          ref: ${{ env.GITHUB_REF_NAME }}

      - uses: actions/checkout@v3
        with:
          path: builder

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Patch build result to a silicon only app
        run: |
          git apply ./builder/silicon-only.patch
          git apply ./builder/yarn-dist-force-arm64.patch

      - name: Install Yarn
        run: |
          # https://yarnpkg.com/getting-started/install
          corepack enable
          yarn install

      - name: Build img
        run: |
          cd packages/app-desktop
          USE_HARD_LINKS=false yarn run dist --publish=never

      - name: Release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: packages/app-desktop/dist/*.dmg
          tag_name: ${{ github.ref_name }}
